base/urls.py
from django.urls import path
from . import views

app_name='base'


urlpatterns = [
    path('',views.index,name='home'),
    path('contact/',views.contact,name='contact'),
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
    path('search/',views.search,name='search'),
    path('requests/',views.requests,name='request'),
    path('logout/',views.user_logout,name='logout'),
]

long_claw/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from base import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/', include('base.urls'))
]

base/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

Blood_type=[('A+','A+'),
    ('B+','B+'),
    ('AB+','AB+'),
    ('O+','O+'),
    ('O-','O-'),
    ('A-','A-'),
    ('B-','B-'),
    ('AB-','AB-')]
account_type=[('Donor','Donor'),('Patient','Patient')]
state_select=[('AL','AL'),
    ('AK','AK'),
    ('AZ','AZ'),
    ('AR','AR'),
    ('CA','CA'),
    ('CO','CO'),
    ('CT','CT'),
    ('DE','DE'),
    ('DC','DC'),
    ('FL','FL'),
    ('GA','GA'),
    ('HI','HI'),
    ('ID','ID'),
    ('IN','IN'),
    ('IA','IA'),
    ('KS','KS'),
    ('KY','KY'),
    ('LA','LA'),
    ('ME','ME'),
    ('MD','MD'),
    ('MA','MA'),
    ('MI','MI'),
    ('MN','MN'),
    ('MS','MS'),
    ('MO','MO'),
    ('MT','MT'),
    ('NE','NE'),
    ('NV','NV'),
    ('NH','NH'),
    ('NJ','NJ'),
    ('NM','NM'),
    ('NY','NY'),
    ('NC','NC'),
    ('ND','ND'),
    ('OH','OH'),
    ('OK','OK'),
    ('OR','OR'),
    ('PA','PA'),
    ('RI','RI'),
    ('SC','SC'),
    ('SD','SD'),
    ('TN','TN'),
    ('TX','TX'),
    ('UT','UT'),
    ('VT','VT'),
    ('VA','VA'),
    ('WA','WA'),
    ('WV','WV'),
    ('WI','WI'),
    ('WY','WY'),
    ]


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    blood_type= models.CharField(max_length=3,choices=Blood_type,default='O+')
    resident_state=models.CharField(max_length=2,choices=state_select,default='AL')
    date_of_birth=models.DateField(blank=True,null=True)
    phone_number=models.CharField(max_length=10)
    registered_as=models.CharField(max_length=7,choices=account_type,default='Donar')
    requested = models.BooleanField(default=False)

    def __str__(self):
        return self.user.email

base/forms.py
from django import forms
from django.contrib.auth.models import User
from base.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password= forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')
        help_texts={'username':None}


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('blood_type','resident_state','date_of_birth','phone_number','registered_as')
        help_texts={'date_of_birth':"(yyyy-mm-dd)"}

base/views.py
from django.shortcuts import render
from base.forms import UserForm,UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
from base.models import UserProfileInfo


def index(request):
    return render(request,'base/home.html',context={})
# Create your views here.
def contact(request):
    return render(request,'base/contact_us.html',context={"print":"contact us page"})

def register(request):
    registered=False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()

            user.set_password(user.password)

            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'base/register.html',
                              {'user_form':user_form,
                              'profile_form':profile_form,
                              'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                p=UserProfileInfo.objects.get(user_id=user)
                if p.registered_as=="Patient":
                    return HttpResponseRedirect(reverse('base:search'))
                elif p.registered_as=="Donor":
                    return HttpResponseRedirect(reverse('base:request'))

                # return HttpResponse("login sucessful")


            else:
                return HttpResponse("account not active")
        else:
            print("fail")
            return HttpResponse("Invalid login")
    else:
        return render(request,'base/user_login.html',{})

@login_required
def search(request):

    current_user=UserProfileInfo.objects.get(user_id=request.user)
    if current_user.registered_as=="Donor":
        return HttpResponseRedirect(reverse('base:request'))
    else:
        object = UserProfileInfo.objects.all().filter(blood_type=current_user.blood_type,
                                                        resident_state=current_user.resident_state)
        object = object.exclude(user_id=request.user)
        object = object.exclude(registered_as="Patient")
        match=False
        if object:
            match=True
            noOfDonor=len(object)
            if request.method=="POST":
                current_user.requested=True
                current_user.save()
                return render(request,'base/search.html',context={"matches":match,
                                                              "Donor":noOfDonor,"r":current_user.requested})
            else:
                return render(request,'base/search.html',context={"matches":match,
                                                              "Donor":noOfDonor,"r":current_user.requested})
        else:
            return render(request,'base/search.html',context={"matches":match})


@login_required
def requests(request):
    current_user=UserProfileInfo.objects.get(user_id=request.user)
    object = UserProfileInfo.objects.all().filter(blood_type=current_user.blood_type,
                                                    resident_state=current_user.resident_state)
    object = object.exclude(registered_as="Donor")
    object = object.exclude(requested=False)
    return render(request,'base/requests.html',context={"request":object})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('base:home'))

templates/base/contact_us.html
{% extends "base/home.html" %}
{% block body_block %}





<div class="contact">
    <h1>About Us</h1>
    <br>
    <h3> Email us: contactplasmapal@gmail.com </h3>
    <br>
    <h4>With PlasmaPal, you can donate your plasma to those in need, or find someone to who can donate you lifesaving plasma!
        PlasmaPal was founded after getting a text from our friend about how she was looking for COVID-19
        recovered patients who could donate plasma as it could help save her mother's life.
        This was very heartbreaking, so we made this platform to connect those individuals.</h4>



</div>
<style>
  .contact{
    border: 7px solid #e0414b;
    border-radius: 10px;
    line-height: 1.8;
    text-indent: 5px;
    letter-spacing: 3px;
    font-family: 'MuseoModerno', sans-serif;
    position: relative;
    z-index:1;
    background: white;
    max-width: 70%;
    margin:  auto ;
    padding: 50px;
    margin-top:100px;
    text-align: center;
    box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);

  }

      @media screen and (max-width:768px) {
        .contact{
          max-width:100%;
          text-align: left;
          padding:2px;
          border: 3px solid #e0414b;
        }
      }


</style>
{% endblock %}

templates/base/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title></title>
    <link rel="stylesheet" href="{% static "base/css/background_animation.css" %}">
    <link rel="stylesheet" href="{% static "base/css/contactus.css" %}">
    <link rel="stylesheet" href="{% static "base/css/footer.css" %}">
    <link rel="stylesheet" href="{% static "base/css/font.css" %}">
    <link rel="stylesheet" href="{% static "base/css/navbar.css" %}">
    <link rel="stylesheet" href="{% static "base/css/pre-loader.css" %}">
    <link rel="stylesheet" href="{% static "base/css/jumbotron.css" %}">
    <link rel="stylesheet" href="{% static "base/css/infobar.css" %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" integrity="sha256-qM7QTJSlvtPSxVRjVWNM2OfTAz/3k5ovHOKmKXuYMO4=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=MuseoModerno&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Exo&display=swap" rel="stylesheet">
  </head>

  <body>


    <div class="loader-Wrapper">
     <div class = "centered">
  	   <div class = "blob-1"></div>
  	   <div class = "blob-2"></div>
     </div>

     </div>



    <nav id="navbar">
     <div class="logo">
      <h4>PlasmaPal</h4>
     </div>
     <ul class="navlinks">
       <li><a id="navlinks" href="{% url "base:home"%}">Home</a></li>
        {% if user.is_authenticated %}
       <li><a id="navlinks" href="{% url "base:search"%}">Search</a></li>
       <li><a id="navlinks" href="{% url "base:logout"%}">Logout</a></li>

       {% else %}
         <li><a id="navlinks" href="{% url "base:register"%}">Register</a></li>
         <li><a id="navlinks" href="{% url "base:user_login"%}">Login</a></li>
       {% endif %}

       <li><a id="navlinks" href="{% url "base:contact"%}">Contact Us</a></li>
     </ul>

     <div class="burger">
       <div class="line1"></div>
       <div class="line2"></div>
       <div class="line3"></div>


     </div>
    </nav>



    <main>
      {% block body_block %}
      <div class="Hero">
          <div class="hero-img" style="">
            <p><img src="{% static "base/img/hero/hero.png" %}"alt=""></p>

          </div>

        <div class="hero-text">
          <h5 data-shadow='PLASMAPAL'>PLASMAPAL</h5><br>
          <h2>Get matched with COVID-19-recovered plasma donors</h2><br>
          <a class="hero-btn" href="{% url "base:register"%}">Sign Up Now!</a>

        </div>
      </div>
<br><br><br><br><br><br><br><br><br><br><br><br>
      <div class="q1">
              <div class="inner">
                  <h1>How your Plasma could save someone's life</h1>
                  <br>
                  <h3>According to the FDA, If you have fully recovered from COVID-19,
                      you may be able to help patients currently fighting the infection
                      by donating your plasma. Because you fought the infection, your plasma
                      now contains COVID-19 antibodies. These antibodies provided one way
                      for your immune system to fight the virus when you were sick, so
                      your plasma may be able to be used to help others fight off the disease.</h3>
                      <br>
                      <a href="https://www.fda.gov/emergency-preparedness-and-response/coronavirus-disease-2019-covid-19/donate-covid-19-plasma" target="_blank">Learn more by clicking here</a>
                      <br><br>
              </div>
          </div>

<div class="q2">
              <div class="inner">
                  <h1>I Haven’t Had COVID-19. What Can I Do to Help?</h2>
                      <br>
                      <h3>You can consider donating blood! One blood donation
                          can save up to three lives. The COVID-19 pandemic has
                          caused unprecedented challenges to the U.S. blood supply.
                           Donor centers have experienced a dramatic reduction in
                           donations due to the implementation of social distancing
                           and the cancellation of blood drives. Blood is needed
                           every day to provide lifesaving treatments to a variety
                           of patients. You can help ensure that blood continues
                           to be available for patients by finding a blood donor
                           center near you to schedule your donation!</h3>
              </div>

</div>






      <div class="info-box">
        <div class="box1 box">
            <p>
              <img id="icon" src="{% static "base/img/icon/002.png" %}" alt="">
            </p>
            <br>
            <br>
            <h1>For Donors</h1>
            <br>
            <a href="#donors">Learn more</a>
          </div>
        <div class="box2 box">
          <p>
            <img id="icon" src="{% static "base/img/icon/003.png" %}" alt="">
          </p>
          <br>
          <h1>For Patients</h1>
          <br>
          <a href="#patients">Learn more</a>
        </div>
        <div class="box3 box">
          <p><img id="icon" src="{% static "base/img/icon/001.png" %}" alt=""></p>
          <br>
          <h1>Connect With Us</h1>
          <p> </p><br>
          <a href="{% url "base:contact"%}">Learn more</a>
        </div>
      </div>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>


      <div class="donor" id="donors">
          <div class="inner">
              <h1 style="text-align: center"> For Donors</h1>
              <br>
              <h2>If you are a COVID-19 recovered patient, your plasma could help treat someone affected by the virus!</h3>
              <br>
              <h3>1. Sign up and fill out all your information accurately.</h2>
              <br>
              <h3>2. We will verify your COVID-19 test results</h2>
              <br>
              <h3>3. Patients who are a match will request to match with you.</h2>
              <br>
              <h3>4. We will reach out to you with the patient information so you can reach out to them and help them battle COVID-19!</h2>


          </div>

      </div>
      <div class="patient" id="patients" >
          <div class="inner">
              <h1 style="text-align: center">For Patients</h1>
              <h2>If you are a patient battling COVID-19, a recovered patient's plasma could help you defeat the virus!</h3>
              <br>
              <h3>1. Sign up and fill out all your information accurately.</h2>
              <br>
              <h3>2. Use the search function to look up eligible donors</h2>
              <br>
              <h3>3. You can request to be matched with eligible donors.</h2>
              <br>
              <h3>4. We will reach out to the donor with your information so they can reach out to you and help you fight COVID-19!</h2>
              <br>
          </div>

      </div>
      <br> <br><br><br><br><br><br><br>

      {% endblock %}
    </main>







      <div class="area" >
            <ul class="circles">
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
            </ul>
     </div >












     <script>
  $(window).on("load",function (){
    $(".loader-Wrapper").fadeOut("slow");
  });

</script>

      <script src="{% static "base/js/navbar.js" %}">

      </script>

  </body>
</html>

templates/base/register.html
{% extends "base/home.html" %}
{% block body_block %}





<div class="form">
  {% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}
    <h1>Register Here</h1>
    <br>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{user_form.as_p}}
      {{profile_form.as_p}}
      <br>
      <input id="button" type="submit" name="" value="Register">

    </form>

  {% endif %}
</div>
<style>
  .form{
    line-height: 1.8;
    letter-spacing: 3px;
    font-family: 'MuseoModerno', sans-serif;
    position: relative;
    z-index:1;
    background: #707bb185;
    max-width: 50%;
    margin:  auto ;
    padding: 3%;
    margin-top:100px;
    text-align: center;
    box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
    border: 7px solid #e0414b;
    border-radius: 25px;
  }
  #button{
    color: black;
    font-size: 1.5em ;
    text-decoration: none;
    padding: 5px;
    border-radius:10px;
    background:none;
  }
  #button:hover,#button:active{
    border: 3px solid #f74c4c;
    border-radius: 10px;
  }

  @media screen and (max-width:768px) {
    .form{

      max-width: 100%;

    }

  }

</style>
{% endblock %}

templates/base/requests.html
{% extends "base/home.html" %}
{% block body_block %}
<div class="request">
{% if request %}
<h3>Requests:</h3>
<br>
<table border=1px id = "table">
  <thead>
      <th><h3>Name</h3></th>
      <th><h3>Email</h3></th>
      <th><h3>Phone Number</h3></th>
      <th><h3>State</h3></th>
  </thead>
  {% for x in request %}
  <tr>
    <td>{{x.user}}</td>
    <td>{{x}}</td>
    <td>{{x.phone_number}}</td>
    <td>{{x.resident_state}}</td>
  </tr>
  {% endfor %}
</table>
{% else %}
<p>No patients found. We will contact you if you have a request!</p>
{% endif %}
<style>
        table {
        border-collapse: collapse;
        margin: auto;
        }

        table, th, td {
        padding:15px;
        border: 2px solid black;
        text-align: center;
        }
        .request{
          line-height: 1.8;
          font-family: 'Roboto', sans-serif;
          position: relative;
          z-index:1;
          background: #707bb185;
          max-width: 50%;
          margin:  auto ;
          padding: 2%;
          margin-top:100px;
          text-align: center;
          box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
          border: 7px solid #e0414b;
          border-radius: 25px;
        }

        @media screen and (max-width:768px) {
          .request{
            max-width: 100%;
            margin-top:100px;
            text-align: center;
          }



        }
        </style>


{% endblock %}

templates/base/search.html
{% extends "base/home.html" %}
{% block body_block %}
<div class="search">
{% if matches %}
  <h3>{{Donor}} matches found</h3>
  {% if not r %}
    <p>press request to send your contact info to the donor</p>
    <form action="{% url 'base:search' %}" method="POST">
      {% csrf_token %}
      <input id="search" type="submit" name="" value="request">
    </form>
  {% else %}
    <p>Your request has been sent to the donor(s)</p>
{% endif %}

{% else %}
<p>No matches found. We will contact you if a donor is found:)</p>
<p>Hang in there!</p>
{% endif %}

</div>


<style>
    .search{
      line-height: 1.8;
      font-family: 'Roboto', sans-serif;
      position: relative;
      z-index:1;
      background: #707bb185;
      max-width: 50%;
      margin:  auto ;
      padding: 2%;
      margin-top:100px;
      text-align: center;
      box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
      border: 7px solid #e0414b;
      border-radius: 25px;
    }
    #search{
      color: black;
      font-size: 1.5em ;
      text-decoration: none;
      padding: 5px;
      border-radius:10px;
      background:none;
    }
    #search:hover,#search:active{
      border: 3px solid #f74c4c;
      border-radius: 10px;
    }

    @media screen and (max-width:768px) {
      .search{

        max-width: 90%;

      }

    }
  </style>

{% endblock %}

templates/base/user_login.html
{% extends "base/home.html" %}
{% block body_block %}
<div class="login">
  <h1>Login</h1>
  <br><br>
  <form action="{% url 'base:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">
    <br>
    <br>
    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="Enter Password">
<br><br><br>
    <input id ="logbutton" type="submit" name="" value="Login">

  </form>

</div>

<style>
    .login{
        line-height: 1.8;
      font-family: 'MuseoModerno', sans-serif;
      position: relative;
      z-index:1;
      background: #707bb185;
      max-width: 50%;
      margin:  auto ;
      padding: 2%;
      margin-top:100px;
      text-align: center;
      box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
      border: 7px solid #e0414b;
      border-radius: 25px;
    }
    #logbutton{
      color: black;
      font-size: 1.5em ;
      text-decoration: none;
      padding: 5px;
      border-radius:10px;
      background:none;
    }
    #logbutton:hover,#logbutton:active{
      border: 3px solid #f74c4c;
      border-radius: 10px;
    }
    @media screen and (max-width:768px) {
      .login{
        max-width: 90%;
      }


    }


  </style>

</style>
{% endblock %}